from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path
from datetime import datetime
import re

@dataclass
class ReformatOptions:
    template: str = "sop"   # sop|debug|note（v0.1 先 sop）
    keep_raw: bool = True

def _title_from_path(p: Path) -> str:
    stem = p.stem.strip()
    return stem if stem else "Untitled"

def reformat_sop(src_text: str, title: str, keep_raw: bool = True) -> str:
    """
    规则版 SOP：不胡编，只做结构化与重排。
    """
    # 简单清洗（保留代码块）
    text = src_text.replace("\r\n", "\n").replace("\r", "\n").strip()

    # 尝试从原文提取第一行标题（如果就是 Markdown 标题）
    first_line = text.splitlines()[0].strip() if text else ""
    if first_line.startswith("#"):
        title = re.sub(r"^#+\s*", "", first_line).strip() or title

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    out = []
    out.append(f"# {title}")
    out.append("")
    out.append(f"> Generated by hx-agent reformat (rule) at {now}")
    out.append("")
    out.append("## 目标")
    out.append("- （从原文中抽取/自行补充）")
    out.append("")
    out.append("## 结论（TL;DR）")
    out.append("- （从原文中抽取/自行补充）")
    out.append("")
    out.append("## 步骤")
    out.append("1. ")
    out.append("")
    out.append("## 关键点 / 注意事项")
    out.append("- ")
    out.append("")
    out.append("## 常见问题 / Debug")
    out.append("- ")
    out.append("")

    # 把原文放到“原始记录”，确保不丢信息
    if keep_raw:
        out.append("## 原始记录")
        out.append("")
        out.append("```text")
        out.append(text)
        out.append("```")
        out.append("")

    return "\n".join(out)

def reformat_text(src_text: str, opt: ReformatOptions, title: str) -> str:
    tpl = (opt.template or "sop").lower()
    if tpl == "sop":
        return reformat_sop(src_text, title=title, keep_raw=opt.keep_raw)
    # v0.1 先不实现其它模板，留后路
    raise ValueError(f"template not supported in v0.1: {tpl}")
